project:
  type: website
  output-dir: docs

website:
  title: "Übungsheft"
  navbar:
    left:
      - href: index.qmd
        text: FAQs
      - href: sections/software/software.qmd
        text: Software und Literatur
      - text: Themenabschnitte
        menu: 
        - href: sections/rechenkompetenzen/rechenkompetenzen.qmd
          text: 1. Grundlegende Rechenkompetenzen
        - href: sections/rechenkompetenzen_diagnostik/rechenkompetenzen_diagnostik.qmd
          text: 2. Rechenkompetenzen der Diagnostik
        - href: sections/diagnostischer_prozess/diagnostischer_prozess.qmd
          text: 3. Der Diagnostische Prozess
        - href: sections/konfidenzintervalle/konfidenzintervalle.qmd
          text: 4. Konfidenzintervalle
        - href: sections/datenmatrizen/datenmatrizen.qmd
          text: 5. Datenmatrizen
        - href: sections/rasch_modell/rasch_modell.qmd
          text: 6. Das Rasch-Modell
        - href: sections/pl2_pl3/pl2_pl3.qmd
          text: 7. 2PL- und 3PL-Modelle
        - href: sections/polytom/polytom.qmd
          text: 8. IRT-Modelle für Polytome Daten
        - href: sections/thurstonian_irt/thurstonian_irt.qmd
          text: 9. Thurstonian IRT
        - href: sections/adaptives_testen/adaptives_testen.qmd
          text: 10. Adaptives Testen
      - href: sections/mitwirkende/mitwirkende.qmd
        text: Mitwirkende

format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true