# Übungsheft zur Vorlesung Diagnostik

Herzlich Willkommen! Im Folgenden finden Sie Antworten auf eine Reihe von FAQs zum Übungsheft der Veranstaltung M.B.2. Wenn Sie sich gleich in die Aufgaben stürzen wollen, finden Sie diese unter dem Reiter Themenabschnitte.

## Was ist das Übungsheft?

Diese Webseite ("Das Übungsheft") ist eine Sammlung von Aufgaben, die wir im Laufe des Semesters parallel zur Vorlesung bearbeiten. Die Aufgaben unterstützen Sie dabei, komplexere Sachverhalte aus der Vorlesung zu verstehen und Ihren Lernerfolg zu überprüfen. Die Aufgaben in diesem Heft dienen also dem Ziel, Sie möglichst direkt auf besonders herausfordernde Teilaspekte der Prüfung vorzubereiten. Wir empfehlen Ihnen entsprechend dringend, das Heft im Laufe des Semesters zu bearbeiten und aktiv in der Übung mitzuarbeiten.

Die Übung ist so strukturiert, dass Sie die Aufgaben eines Abschnitts in Ruhe zuhause bearbeiten und anschließend in der Sitzung Fragen stellen können. Wenn es in den Sitzungen keine Fragen zum Übungsheft gibt, beschäftigen wir uns mit weiteren Übungsaufgaben oder darüber hinausgehenden Inhalten.

## Was ist das Übungsheft nicht?

- Das Übungsheft ist nicht wichtiger als die Vorlesung. Es behandelt nur eine Teilmenge der Vorlesungsinhalte. Wir fokussieren uns dabei auf Themen, die Studierenden erfahrungsgemäß eher schwerfallen. Themen der Vorlesung, die nicht im Übungsheft behandelt werden, werden ebenfalls Teil der Prüfung sein.

- Das Übungsheft ist kein Lehrbuch. An einigen Stellen enthält das Heft Erklärungen des Stoffs. Es ist aber nicht der Anspruch, dass das notwendige Wissen, um die Aufgaben zu lösen, im Heft enthalten ist. Diesen Zweck erfüllen die Präsenzveranstaltungen (Vorlesung und Übung).

## Wo bekomme ich Hilfe zu den Aufgaben?

Die erste Anlaufstelle ist die Präsenzveranstaltung der Übung. Alle anderen Fragen können Sie in das OLAT-Forum der Veranstaltung posten. So können alle Teilnehmer:innen von den Antworten profitieren. Unsere Vorstellung der Übung sieht vor, dass das Wissen zu den Aufgaben für alle Studierenden gleichermaßen verfügbar ist. Bitte stellen Sie Ihre Fragen daher auch nur über das Forum und nicht via Mail. Sie sind natürlich herzlich eingeladen, auch selbst Fragen Ihrer Kommiliton:innen im Forum zu beantworten.

## Was soll ich tun, wenn ich mit den Aufgaben nicht hinterherkomme?

Auch wenn das die Idealvorstellung wäre, kann es passieren, dass Sie es im Semester nicht schaffen, alle Aufgaben parallel zur Vorlesung zu bearbeiten. Davon geht die Welt nicht unter. Wir raten Ihnen in diesem Fall dazu, in dem Rahmen, der für Sie schaffbar ist, Teile der wöchentlichen Aufgaben zu erledigen. Das funktioniert erfahrungsgemäß viel besser, als sich vorzunehmen, das Heft in den Semesterferien alleine durchzuarbeiten.

## Muss ich das Übungsheft bearbeiten, um die Übung M.B.2 zu bestehen?

Nein, das Bearbeiten des Übungshefts ist keine Voraussetzung, um die Übung M.B.2 zu bestehen. Es gibt auch keine Anwesenheitspflicht. Analysen der Prüfungsnoten und Übungsbeteiligung aus früheren Semestern haben aber gezeigt, dass Studierende, die die Übungsaufgaben bearbeiten deutlich besser in der Prüfung abschneiden als diejenigen, die das nicht tun.

## Wie sollte man mit den Lösungen umgehen?

Bitte schauen Sie erst in die Lösungen, wenn Sie die Aufgabe fertig bearbeitet haben oder überhaupt keinen Ansatz finden. Der Lerneffekt durch das Lösen von Aufgaben entsteht nicht vorrangig dadurch, dass Sie eine spezifische Aufgabe lösen können, sondern darin, Lösungsansätze auszuprobieren und auf diesem Weg den Stoff durch den Blickwinkel der Aufgabe neu zu betrachten.

## Geht es jetzt endlich los?

Klar! Zu allerletzt wünschen wir Ihnen viel Erfolg bei der Bearbeitung der Aufgaben und hoffen, im Laufe des Semesters auch etwas Interesse an den Themen der Testtheorie und Diagnostik wecken zu können. : -\)