{
  "hash": "f0b5bc882e002c3a8cb36e54960e1a45",
  "result": {
    "engine": "knitr",
    "markdown": "# Rechenkompetenzen der Diagnostik\n\nBelastbare psychologische Diagnostik ist an vielen Stellen auf diagnostische Rechenkompetenzen angewiesen. Im Folgenden werden einige dieser Kompetenzen geübt.\n\n## Ablesen und Berechnen von Normwerten\n\n### Aufgaben mit der BDI-II Norm\n\nTestwerte lassen sich durch den Vergleich mit einer Normstichprobe interpretieren. Im einfachsten Fall liegen dafür Normtabellen vor. Im Folgenden finden Sie den Auszug einer Normtabelle für den BDI-II:\n\n![](images/bdi_norm.png)\n\nRoelofs, J., Van Breukelen, G., De Graaf, L. E., Beck, A. T., Arntz, A., \\& Huibers, M. J. H. (2013). Norms for the Beck Depression Inventory (BDI-II) in a large dutch community sample. \\textit{Journal of Psychopathology and Behavioral Assessment}, 35(1), 93–98. https://doi.org/10.1007/s10862-012-9309-2\n\n#### Werte ablesen\n\n::: {.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\nIn einer Studie wird der Zusammenhang zwischen Schlafgewohnheiten und depressiven Symptomen untersucht. In einer Subanalyse soll auf die Bevölkerung der $40\\%$ betroffensten Frauen mit hohen Bildungsabschlüssen rückgeschlossen werden. Ob eine Person mit in die Analyse mit aufgenommen wird, soll anhand ihres BDI-II Scores entschieden werden. Ab welchem BDI-II Score sollte eine Frau mit hohem Bildungsabschluss in die Analyse aufgenommen werden?\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\nPersonen mit einem BDI-II Score $>7$ sollten in die Analyse mit aufgenommen werden.\n\n:::\n\n#### Rohwerte transformieren\n\nEs gibt verschiedene Normwerteverteilungen (z, IQ, T, SW, etc.), die anhand von Mittelwert und Standardabweichungen definiert sind. Wenn Mittelwert und Standardabweichung der Testwerte in einer Normstichprobe bekannt sind, können die Testwerte entsprechend normiert werden.\n\n| Normbezeichnung       | Transformation                                    |\n|-----------------------|--------------------------------------------------|\n| z-Skala               | $z_i = \\frac{x_i - \\overline{x}}{SD(x)}$         |\n| IQ-Abweichungsskala   | $IQ_i = 100 + 15 z_i$                            |\n| T-Werte               | $T_i = 50 + 10 z_i$                              |\n| Standardwerte         | $SW_i = 100 + 10 z_i$                            |\n| PISA-Skala            | $P_i = 500 + 100 z_i$                            |\n| Stanine-Normwert      | $S_i \\approx 5 + 2 z_i$                          |\n| Prozentrang           | $PR_i = 100 \\frac{freq_{\\text{cum}}(X_i)}{N}$    |\n\n::: {.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\nEine Person erzielt einen Testwert von $36$. In der Normstichprobe weisen die Testwerte einen Mittelwert von $\\overline{x} = 31$ und eine Standardabweichung von $SD(x) = 5$ auf.\n\n(a) Welchen z-Wert hat die Person im Vergleich zur Normstichprobe?\n\n(b) Der z-Wert lässt sich anhand der Formeln in andere Normwerte transformieren. Welcher T-Wert ergibt sich daraus?\n\n:::\n\n::: {.callout-tip title=\"Lösung (a)\" collapse=\"true\"}\n\nGegeben:\n\n$x = 36$\n\n$\\overline{x} = 31$\n\n$SD(x) = 5$\n\nGesucht:\n\n$z = \\frac{x - \\overline{x}}{SD(x)} = \\frac{36 - 31}{5} = 1$\n\n:::\n\n::: {.callout-tip title=\"Lösung (b)\" collapse=\"true\"}\n\nGegeben:\n\n$z = 1$\n\nGesucht:\n\n$T = 50 + 10z = 50 + 10 = 60$\n\n:::\n\n### Prozentränge in R berechnen\n\nNutzen Sie den Code um die Daten der darunter folgenden Abbildung zu samplen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(101)\n\t\t\n# Daten samplen\nN <- 100\nx <- rnorm(N, 2, 5)\nx <- round(x)\n```\n:::\n\n\nHistogramm:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](rechenkompetenzen_diagnostik_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\nBerechnen Sie die Prozentränge in R und überprüfen Sie Ihr Ergebnis anhand der Abbildung.\n\n:::\n\nProzentränge:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](rechenkompetenzen_diagnostik_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n::: {.callout .callout-tipp title=\"Tipp\" collapse=true}\n\nSie benötigen die Funktionen `{{r}} table` und `{{r}} cumsum`.\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(101)\n\t\t\n# Daten samplen\nN <- 100\nx <- rnorm(N, 2, 5)\nx <- round(x)\n\n# Prozentränge berechnen\ncumsum(table(x) / N)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-10  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8   9  10 \n  1   3   5   6  12  15  17  25  30  35  45  52  60  72  77  83  86  92  96  99 \n 11 \n100 \n```\n\n\n:::\n:::\n\n\n:::\n\n### Normwerttransformation in einem Fallbeispiel\n\nDie Lesefähigkeit von Emilia wurde mit Hilfe eines validierten Leistungstests für Kinder erhoben. Um Emilias Leistung mit der Leistung von 9-Klässlerinnen in Rheinland-Pfälzer Gymnasien vergleichbar zu machen, wurde ihre Punktzahl von der leitenden Diagnostikerin zu einem $T$-Wert von $T = 56$ transformiert.\n\n::: {.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\n(a) Berechnen Sie Emilias Leistung als IQ-Wert.\n\n(b) Berechnen Sie den Prozentrang von Emilia innerhalb ihrer Schulklasse. In der Abbildung finden Sie dazu Häufigkeiten der T-Normwerte der Schüler:innen in Emilias Klasse.\n\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](rechenkompetenzen_diagnostik_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Lösung (a)\" collapse=\"true\"}\n\nGegeben:\n\n$T = 56$\n\nGesucht:\n\n$IQ = 100 + 15z$\n\n$z = \\frac{T - 50}{10}$\n\nAlso $IQ = 100 + 15 \\cdot \\Big(\\frac{T - 50}{10}\\Big) = 109$\n\n:::\n\n::: {.callout-tip title=\"Lösung (b)\" collapse=\"true\"}\n\nGesucht:\n\n$PR = 100 \\cdot \\frac{freq_{cum}(x)}{N}$\n\n$x = 56$\n\nAbgelesen:\n\n$freq_{cum}(56) = 5$\n\n$N = 15$\n\nAlso $PR = 100 \\frac{5}{15} \\approx 33.33$\n\n:::\n\n### Erstellen einer Normtabelle\n\nDie nächste Aufgabe ist etwas länger als die anderen. Sie werden in diesem Abschnitt Daten in R simulieren und selbst eine Normtabelle für einen Test erstellen.\n\nStellen Sie sich vor, Sie hätten in einem Forschungsprojekt einen Test mit drei Items entwickelt - zum Beispiel ein Screening Instrument zur Detektion von Spinnenangst. $N = 1000$ Personen aus der Gesamtbevölkerung bewerteten die drei Items auf einer fünfstufigen Ratingskala (stimme nicht zu, stimme eher nicht zu, weder noch, stimme eher zu, stimme zu). Alle Items sind positiv gepolt.\n\nIhre Aufgabe wird es sein, anhand dieser Daten eine Normtabelle zu generieren, die nach Geschlecht (Mann, Frau, Divers) und fünf Altersbändern ([18, 25), [25, 35), [35, 45), [45, 55), [55, 65)) differenziert. Anwender:innen sollten anhand der Tabelle Summenscores in Standardwerte umwandeln können. Die folgenden Aufgaben leiten Sie schrittweise zu diesem Ergebnis.\n\nDer erste Schritt ist es, die Antworten der $N = 1000$ Versuchspersonen in Ihrer R-Session zu generieren. Da es sich um ein fiktives Beispiel handelt, können wir selbst Übungsdaten simulieren. Genau das ist Ihre erste Aufgabe.\n\n::: {.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\nKopieren Sie den folgenden Code-Abschnitt in Ihre IDE (z.B. RStudio) und führen sie den Code vollständig aus. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Seed setzen\nset.seed(5546)\n\n# Anzahl der Personen\nN <- 1000\n\n# Anzahl der Items\nI <- 3\n\n# Geschlecht der Personen festlegen\ngeschlecht <- sample(\n  x = c(\"mann\", \"frau\", \"divers\"),\n  size = N, \n  replace = TRUE,\n  prob = c(0.46, 0.46, 0.08)\n  )\n\n# Altersgruppe der Personen festlegen\nalter <- sample(\n  x = c(\"[18, 25)\", \"[25, 35)\", \"[35, 45)\", \"[45, 55)\", \"[55, 65)\"),\n  size = N,\n  replace = TRUE,\n  prob = c(0.15, 0.25, 0.25, 0.20, 0.15)\n)\n\n# Fragebogenantworten simulieren\nU <- teachIRT::sim_pcm(n = N, m = I, m_star = 4) + 1\n\n# Fragebogenantworten und Datensatz mergen\ndat <- dplyr::bind_cols(\n  person = 1:N,\n  geschlecht = geschlecht,\n  alter = alter,\n  U\n  )\n\n# Oberste zehn Zeilen des Datensatzes anzeigen\ndat <- dplyr::as_tibble(dat)\nprint(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 6\n   person geschlecht alter    item_1 item_2 item_3\n    <int> <chr>      <chr>     <dbl>  <dbl>  <dbl>\n 1      1 mann       [35, 45)      4      3      4\n 2      2 mann       [45, 55)      4      5      5\n 3      3 frau       [25, 35)      4      4      3\n 4      4 frau       [45, 55)      2      1      1\n 5      5 mann       [35, 45)      4      5      2\n 6      6 mann       [25, 35)      3      2      2\n 7      7 frau       [35, 45)      3      3      1\n 8      8 mann       [55, 65)      3      5      4\n 9      9 frau       [55, 65)      4      3      4\n10     10 mann       [18, 25)      4      4      3\n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\n:::\n\nNun sollten Sie in Ihrer R-Session auf den Datensatz `dat` zugreifen können. Da Sie zu Beginn mit dem Befehl `set.seed()` einen bestimmten Startwert für die Zufallsziehungen im Code-Abschnitt festlegen, sollten Sie, wenn Sie den Code-Abschnitt wiederholt vollständig ausführen auch immer wieder die gleichen Daten generieren.\n\nZuerst verschaffen wir uns einen Überblick über den Datensatz. Versuchen Sie Folgendes herauszufinden:\n\n::: {.callout-aufgabe}\n\na. Welche Variablen hat der Datensatz?\n\nb. Welche möglichen Werte haben die Variablen jeweils?\n\nc. Wie viele Zeilen hat der Datensatz?\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n**Welche Variablen hat der Datensatz?**\n\nUm das herauszufinden, kann man den Befehl `colnames(dat)` verwenden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"person\"     \"geschlecht\" \"alter\"      \"item_1\"     \"item_2\"    \n[6] \"item_3\"    \n```\n\n\n:::\n:::\n\n\n**Welche möglichen Werte haben die Variablen jeweils?**\n\n`dat$person` enthält natürliche Zahlen von $1$ bis $1000$ und kodiert, zu welcher Person eine Zeile jeweils gehört. Hier die ersten 10 Personen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$person[1:10]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  2  3  4  5  6  7  8  9 10\n```\n\n\n:::\n:::\n\n\nDie möglichen Werte (und Häufigkeiten) der Geschlechtsvariable, `dat$geschlecht`, und der Altersvariable, `dat$alter`, können Sie sich so anzeigen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dat$geschlecht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ndivers   frau   mann \n    60    452    488 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(dat$alter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[18, 25) [25, 35) [35, 45) [45, 55) [55, 65) \n     153      235      251      191      170 \n```\n\n\n:::\n:::\n\n\nDie Variablen `dat$item_1` bis `dat$item_5` enthalten die Antworten auf die fünf Fragebogenitems:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dat$item_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5 \n 58 225 391 256  70 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(dat$item_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5 \n 59 215 389 264  73 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(dat$item_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   2   3   4   5 \n 74 237 340 258  91 \n```\n\n\n:::\n:::\n\n\n**Wie viele Zeilen hat der Datensatz?**\n\nDafür können wir den Befehl `nrow()` verwenden.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1000\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-aufgabe}\n\nWenn Sie der Struktur dieser Aufgabe folgen, werden Sie recht kleinschrittig zur fertigen Normtabelle geleitet. Überlegen Sie dennoch vorher selbst, welche Schritte Sie unternehmen müssten, um aus den simulierten Daten eine Tabelle zu erzeugen, die es Ihnen ermöglicht, jeden Rohwert in einen Standardwert zu transformieren.\n\n:::\n\n\nIm nächsten Schritt Berechnen Sie aus den Antworten auf die drei Items für jede Person einen Summenscore. Später in der Vorlesung und Übung werden Sie Alternativen zum Summenscore kennenlernen. Für diese Aufgabe wird es aber ausreichen, Test-Scores durch einfache Summen zu erzeugen.\n\n::: {.callout-aufgabe}\n\nErzeugen Sie eine neue Variable `dat$score` im Datensatz, indem Sie die Antworten auf die drei Items summieren.\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp\" collapse=true}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$score <- ...\n```\n:::\n\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$score <- dat$item_1 + dat$item_2 + dat$item_3\n```\n:::\n\n\n:::\n\nWenn wir nun den Datensatz anzeigen, ist die neue Variable `score` zu sehen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,000 × 7\n   person geschlecht alter    item_1 item_2 item_3 score\n    <int> <chr>      <chr>     <dbl>  <dbl>  <dbl> <dbl>\n 1      1 mann       [35, 45)      4      3      4    11\n 2      2 mann       [45, 55)      4      5      5    14\n 3      3 frau       [25, 35)      4      4      3    11\n 4      4 frau       [45, 55)      2      1      1     4\n 5      5 mann       [35, 45)      4      5      2    11\n 6      6 mann       [25, 35)      3      2      2     7\n 7      7 frau       [35, 45)      3      3      1     7\n 8      8 mann       [55, 65)      3      5      4    12\n 9      9 frau       [55, 65)      4      3      4    11\n10     10 mann       [18, 25)      4      4      3    11\n# ℹ 990 more rows\n```\n\n\n:::\n:::\n\n\nIn den vorherigen Rechenaufgaben haben Sie verwendet, dass man einen Score in einen beliebigen Normwert transformieren kann, wenn man den Mittelwert und die Standardabweichung der Scores in Normstichprobe kennt. In der nächsten Aufgabe werden Sie daher Mittelwert und Standardabweichung für jede Kombination von Geschlecht und Altersbändern berechnen.\n\n::: {.callout-aufgabe}\n\nBerechnen Sie für jede Kombination von Geschlecht und Altersband einen mittleren Score und eine Standardabweichung der Scores. Das Ergebnis sollte ein `data.frame` (oder `tibble`) mit den Spalten `geschlecht`, `alter`, `score_mean` (Mittelwert in der Zelle), `score_sd` (Standardabweichung in der Zelle) sein. Nennen Sie den data.frame `dstats`.\n\n:::\n\nFür diesen Schritt können Sie auch die Lösung kopieren, falls Sie selten mit R arbeiten.\n\n::: {.callout .callout-tipp title=\"Tipp\" collapse=true}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mittelwert\nm <- aggregate(score ~ geschlecht + ???, dat, mean)\n\n# Standardabweichung\ns <- aggregate(???, dat, ???)\n\n# Neu berechnete Spalten umbenennen\nnames(m)[3] <- \"score_mean\"\nnames(s)[3] <- \"score_sd\"\n\n# Zu dstats mergen\ndstats <- merge(???, s, by = c(???, \"alter\"))\n```\n:::\n\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mittelwert\nm <- aggregate(score ~ geschlecht + alter, dat, mean)\n\n# Standardabweichung\ns <- aggregate(score ~ geschlecht + alter, dat, sd)\n\n# Neu berechnete Spalten umbenennen\nnames(m)[3] <- \"score_mean\"\nnames(s)[3] <- \"score_sd\"\n\n# Zu dstats mergen\ndstats <- merge(m, s, by = c(\"geschlecht\", \"alter\"))\n\n# Optional für schöneres Printing in tibble umwandeln:\ndstats <- dplyr::as_tibble(dstats)\n```\n:::\n\n\n:::\n\n::: {.callout .callout-tipp title=\"Exkurs\" collapse=true}\n\nWenn Sie planen noch lange mit R zu arbeiten, lohnt sich an dieser Stelle ein Blick in das [https://tidyverse.org/](tidyverse). Mit dem Paket `dplyr` gelangen Sie folgendermaßen an das gleiche Ziel:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\ndstats <- dat |> \n\n  # Daten gruppieren\n  group_by(geschlecht, alter) |> \n\n  # Mittelwert und Standardabweichung berechnen\n  summarise(\n    score_mean = mean(score),\n    score_sd = sd(score),\n    .groups = \"drop\"\n    )\n```\n:::\n\n\nDie Denkweise beliebig zu gruppieren und dann Zeilen in Gruppen zusammenzufassen finde ich persönlich etwas angenehmer.\n\n:::\n\nDer resultierende `data.frame` sollte so aussehen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(dstats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 4\n   geschlecht alter    score_mean score_sd\n   <chr>      <chr>         <dbl>    <dbl>\n 1 divers     [18, 25)       8.55     1.63\n 2 divers     [25, 35)       8        2.36\n 3 divers     [35, 45)       8.35     3.10\n 4 divers     [45, 55)       8.82     2.32\n 5 divers     [55, 65)      10.1      2.39\n 6 frau       [18, 25)       9        2.58\n 7 frau       [25, 35)       9.44     2.35\n 8 frau       [35, 45)       9.51     2.43\n 9 frau       [45, 55)       9.08     2.32\n10 frau       [55, 65)       9.13     2.04\n11 mann       [18, 25)       9.49     2.39\n12 mann       [25, 35)       8.97     2.31\n13 mann       [35, 45)       9.06     2.32\n14 mann       [45, 55)       9.39     2.32\n15 mann       [55, 65)       9.06     2.43\n```\n\n\n:::\n:::\n\n\nFür jede Kombination der Geschlechts- und Altersvariable können Sie nun den Score-Mittelwert und die Standardabweichung ablesen. Diese Information ist ausreichend, um Summenscores (/Rohwerte) in z-Werte und anschließend in Standardwerte umzuwandeln. Berechnen Sie vor der Erstellung der gesamten Tabelle ein einzelnes Wertebeispiel.\n\n::: {.callout-aufgabe}\n\nBerechnen Sie den Standardwert einer 32-jährigen Frau mit einem Summenscore von $4$.\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\nGegeben:\n\n$x_i = 4$ Summenscore\n\n$\\overline{x} = 9.44$ Score-Mittelwert in der Normstichprobe\n\n$SD(x) = 2.35$ Score-Standardabweichung in der Normstichprobe\n\nGesucht:\n\n$SW_i = 100 + 10 \\cdot z_i$ Standardwert\n\nBerechnung:\n\n$z_i = \\frac{x_i - \\overline{x}}{SD(x)} = \\frac{4 - 9.44}{2.35}$\n\n$SW_i = 100 + 10 \\cdot \\frac{4 - 9.44}{2.35}$\n\nMit dem Taschenrechner:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_i <- (4 - 9.44) / 2.35\nSW_i <- 100 + 10 * z_i\nprint(SW_i)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 76.85106\n```\n\n\n:::\n:::\n\n\nGerundet ergibt sich $SW_i \\approx 76.85$, ein weit unterdurchschnittlicher Wert.\n\n:::\n\nNun können wir uns an die gesamte Tabelle machen. Überlegen Sie dafür zuerst, welcher Wert der minimal erreichbare Summenscore und welcher der maximal erreichbare Summenscore wäre.\n\n::: {.callout-aufgabe}\n\nWas sind jeweils der minimal und maximal erreichbare Summenscore im Beispiel?\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\nDen kleinstmöglichen Wert erhalten Sie, wenn Sie in allen drei Items Kategorie $1$ wählen, also $1 + 1+ 1 = 3$.\n\nDen höchstmöglichen Wert erhalten Sie, wenn Sie in allen drei Items Kategorie $5$ wählen, also $5 + 5 + 5 = 15$.\n\nDie Spanne/Range der simulierten Summenscores spiegelt diese Überlegung wider:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(dat$score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  3 15\n```\n\n\n:::\n:::\n\n\n:::\n\nWir benötigen also für jede Kombination von Geschlecht und Alter sowie jeden Summenscore zwischen 3 und 15 einen Standardwert. Um die Aufgabe etwas zu reduzieren, können Sie sich auf die möglichen Scores $8, 10, 12$ beschränken.\n\n::: {.callout-aufgabe}\n\nBerechnen Sie für jede Kombination von Geschlecht und Altersband den Standardwert der Summenscores $8$, $10$ und $12$.\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp\" collapse=true}\n\nBei dieser Aufgabe müssen Sie für jeden möglichen Summenscore ($8$, $10$, $12$) eine Spalte an `dstats` anfügen, die Standardwerte enthält.\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp: z-Werte für Rohwert 8\" collapse=true}\n\nAls Zwischenschritt ist es sinnvoll, zunächst z-Werte für jede Kombination von Geschlecht und Altersband zu berechnen. Das geht für einen Summenscore von $8$ so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndstats$z_8 <- (8 - dstats$score_mean)/dstats$score_sd\n```\n:::\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp: Standardwerte für Rohwert 8\" collapse=true}\n\nAls nächstes muss man die z-Werte mit der Formel $SW_i = 100 + 10 \\cdot z_i$ in Standardwerte transformieren. So geht das im Fall eines Summenscores von $8$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndstats$sw_8 <- 100 + 10*dstats$z_8\n```\n:::\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# z-Werte berechnen\ndstats$z_8 <- (8 - dstats$score_mean)/dstats$score_sd\ndstats$z_10 <- (10 - dstats$score_mean)/dstats$score_sd\ndstats$z_12 <- (12 - dstats$score_mean)/dstats$score_sd\n\n# Standardwerte berechnen\ndstats$sw_8 <- 100 + 10*dstats$z_8\ndstats$sw_10 <- 100 + 10*dstats$z_10\ndstats$sw_12 <- 100 + 10*dstats$z_12\n\n# z-Wert wieder löschen\ndstats$z_8 <- NULL\ndstats$z_10 <- NULL\ndstats$z_12 <- NULL\n```\n:::\n\n:::\n\nDie fertige Normtabelle sollte etwa so aussehen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(dstats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 7\n   geschlecht alter    score_mean score_sd  sw_8 sw_10 sw_12\n   <chr>      <chr>         <dbl>    <dbl> <dbl> <dbl> <dbl>\n 1 divers     [18, 25)       8.55     1.63  96.7 109.   121.\n 2 divers     [25, 35)       8        2.36 100   108.   117.\n 3 divers     [35, 45)       8.35     3.10  98.9 105.   112.\n 4 divers     [45, 55)       8.82     2.32  96.5 105.   114.\n 5 divers     [55, 65)      10.1      2.39  91.2  99.6  108.\n 6 frau       [18, 25)       9        2.58  96.1 104.   112.\n 7 frau       [25, 35)       9.44     2.35  93.9 102.   111.\n 8 frau       [35, 45)       9.51     2.43  93.8 102.   110.\n 9 frau       [45, 55)       9.08     2.32  95.3 104.   113.\n10 frau       [55, 65)       9.13     2.04  94.4 104.   114.\n11 mann       [18, 25)       9.49     2.39  93.7 102.   111.\n12 mann       [25, 35)       8.97     2.31  95.8 104.   113.\n13 mann       [35, 45)       9.06     2.32  95.4 104.   113.\n14 mann       [45, 55)       9.39     2.32  94.0 103.   111.\n15 mann       [55, 65)       9.06     2.43  95.6 104.   112.\n```\n\n\n:::\n:::\n\n\n::: {.callout-aufgabe}\n\nLesen Sie zuletzt den Standardwert eines 45-jährigen Mannes mit einem Summenscore von 12 ab.\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n$111$\n\n:::\n\n::: {.callout-aufgabe}\n\nZu Beginn diser Aufgabe sollten Sie selbst überlegen, welche Schritte Sie unternehmen müssten, um aus den Daten eine Normtabelle zu erzeugen. Vergleichen Sie nun Ihre Erwartung mit den durchgeführten Schritten.\n\n:::\n\n## Sensitivität, Spezifität, ROC-Kurven, Youden-Index\n\nLeider sind Diagnosen nicht immer zutreffend. Es kann durchaus passieren, dass eine Person, die eigentlich geeignet wäre, als ungeeignet klassifiert wird. Genauso kann es passieren, dass eine Person, die eigentlich ungeeignet ist, als geeignet klassifiziert wird.\n\n### Tabelle aller möglichen Zustände\n\n::: {.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\n(a) Erstellen Sie eine Tabelle aller möglichen Kombinationen aus wahren Zuständen ${\\text{geeignet}, \\text{ungeeignet}}$ und Diagnosen ${\\text{geeignet}, \\text{ungeeignet}}$.\n\n(b) Benennen Sie jede der vier Kombinationen. Verwenden Sie dazu die folgenden Begriffe:\n\t\n- Falsch positiv (FP)\n- Richtig positiv (RP)\n- Falsch negativ (FN)\n- Richtig negativ (RN)\n- False negative (FN)\n- False positive (FP)\n- True negative (TN)\n- True positive (TP)\n\n(c) Nehmen Sie an, dass eine Person mit einem Testwert $>20$ als geeignet eingestuft wird. Finden Sie einen beispielhaften Testwert für jeden der vier Zustände.\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp: Tabellengerüst\" collapse=true}\n\nSo soll die Tabelle am Ende aussehen:\n\n| Wahrer Zustand | Testwert Beispiel | Diagnose   | Prüfung [De] | Prüfung [Eng] |\n|----------------|-------------------|------------|--------------|---------------|\n|                |                   |            |              |               |\n|                |                   |            |              |               |\n|                |                   |            |              |               |\n|                |                   |            |              |               |\n\nJetzt fehlen noch die Werte.\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp: Teile von a. vorgeben\" collapse=true}\n\n| Wahrer Zustand | Testwert Beispiel | Diagnose   | Prüfung [De] | Prüfung [Eng] |\n|----------------|-------------------|------------|--------------|---------------|\n| Geeignet       |                   |            |              |               |\n|                |                   | Ungeeignet |              |               |\n| Ungeeignet     |                   |            |              |               |\n|                |                   | Ungeeignet |              |               |\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp: Teile von b. vorgeben\" collapse=true}\n\n| Wahrer Zustand | Testwert Beispiel | Diagnose   | Prüfung [De] | Prüfung [Eng] |\n|----------------|-------------------|------------|--------------|---------------|\n| Geeignet       |                   |            | RP           |               |\n|                |                   | Ungeeignet |              | FN            |\n| Ungeeignet     |                   |            |              |               |\n|                |                   | Ungeeignet |              |               |\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n: Tabelle aller Kreuzungen von wahren Zuständen und Diagnosen (dichotom)\n\n| Wahrer Zustand | Testwert Beispiel | Diagnose   | Prüfung [De] | Prüfung [Eng] |\n|----------------|------------------|------------|--------------|---------------|\n| Geeignet       | $21$             | Geeignet   | RP           | TP            |\n| Geeignet       | $20$           | Ungeeignet | FN           | FN            |\n| Ungeeignet     | $23$           | Geeignet   | FP           | FP            |\n| Ungeeignet     | $13$             | Ungeeignet | RN           | TN            |\n\n:::\n\n### Formeln für Sensivität und Spezifität\n\nErgänzen Sie die Formeln für die Sensitivität und Spezifität. Versuchen Sie es zuerst ohne die Vorlesungsfolien und überprüfen Sie dann Ihr Ergebnis.\n\n:::{.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\n$\\text{Sensitivität} = \\frac{RP}{? + ?}$\n\n$\\text{Spezifität} = \\frac{?}{? + RN}$\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\n$\\text{Sensitivität} = \\frac{RP}{RP + FN}$\n\n$\\text{Spezifität} = \\frac{RN}{FP + RN}$\n\n:::\n\n### Sensitivität und Spezifität in einem Beispiel berechnen\n\n::: {.callout-aufgabe title=\"Aufgabe: Runden auf zwei Nachkommastellen\"}\n\nEine Schule möchte einen neuen Test verwenden, um hochbegabte Schüler:innen frühzeitig zu identifizieren. Ein etablierter Intelligenztest wird als Vergleichsstandard zur Überprüfung der Testvorhersagen herangezogen. Die Testergebnisse für eine Stichprobe von 500 Kindern sind:\n\n| Urteil neuer Test   | Urteil etablierter Test | $n$  |\n|---------------------|--------------------------|------|\n| Hochbegabt          | Hochbegabt              | $10$ |\n| Hochbegabt          | Nicht hochbegabt        | $3$  |\n| Nicht hochbegabt    | Nicht hochbegabt        | $482$|\n| Nicht hochbegabt    | Hochbegabt              | $5$  |\n\nBerechnen Sie die Sensitivität und Spezifität des neuen Tests.\n\n::: \n\n::: {.callout .callout-tipp title=\"Tipp\" collapse=true}\n\nGegeben:\n\n$RP = ?$\n\n$FP = ?$\n\n$RN = ?$\n\n$FN = ?$\n\nGesucht:\n\nSensitivität $= \\frac{RP}{RP + FN} = ?$\n\nSpezifität $= \\frac{RN}{FP + RN} = ?$\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\nGegeben:\n\n$RP = 10$\n\n$FP = 3$\n\n$RN = 482$\n\n$FN = 5$\n\nGesucht:\n\nSensitivität $= \\frac{RP}{RP + FN} = \\frac{10}{10 + 5} \\approx .67$\n\nSpezifität $= \\frac{RN}{FP + RN} = \\frac{482}{3 + 482} \\approx .99$\n\n:::\n\n### Den Youden-Index berechnen\n\nDie Testwerte ungeeigneter Testpersonen sind normalverteilt mit $X_u \\sim N(-1.5, 3)$. Die Testwerte geeigneter Testpersonen sind normalverteilt mit $X_g \\sim N(4, 3)$. Eine Person wird als geeignet klassifiziert, wenn Sie einen Testwert $>3$ aufweist. In der Abbildung sehen Sie die Dichterverteilungen der Testwerte ungeeigneter und geeigneter Personen.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](rechenkompetenzen_diagnostik_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nDie gelb markierte Fläche umfasst $93\\%$ der Fläche unter der linken Verteilung. Die blau markierte Fläche umfasst $63\\%$ der Fläche unter der rechten Verteilung.\n\n::: {.callout-aufgabe}\n\nBerechnen Sie den Youden-Index.\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp 1\" collapse=true}\n\nGegeben:\n\n$RN = ?$\n\n$RP = ?$\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp 2\" collapse=true}\n\nGesucht:\n\nSensitivität $=?$\n\nSpezifität $=?$\n\nYouden-Index $=?$\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp 3\" collapse=true}\n\nGegeben:\n\n$RN = ?$\n\n$RP = ?$\n\nGesucht:\n\nSensitivität $= \\frac{RP}{FN + RP} = ?$\n\nSpezifität $= \\frac{RN}{FP + RN} = ?$\n\n$\\text{Youden-Index} = \\text{Sensitivität} + \\text{Spezifität} - 1 = ?$\n\n:::\n\n::: {.callout .callout-tipp title=\"Tipp 4: RN und RP vorgeben\" collapse=true}\n\nGegeben:\n\n$RN = .93$\n\n$RP = .63$\n\nGesucht:\n\nSensitivität $= \\frac{RP}{FN + RP} = ?$\n\nSpezifität $= \\frac{RN}{FP + RN} = ?$\n\n$\\text{Youden-Index} = \\text{Sensitivität} + \\text{Spezifität} - 1 = ?$\n\n:::\n\n::: {.callout-tip title=\"Lösung\" collapse=\"true\"}\n\nGegeben:\n\n$RN = .93$\n\n$RP = .63$\n\nGesucht:\n\nSensitivität $= \\frac{RP}{FN + RP} = \\frac{.63}{(1-.63) + .63} = .63$\n\nSpezifität $= \\frac{RN}{FP + RN} = \\frac{.93}{(1-.93) + .93} = .93$\n\n$\\text{Youden-Index} = \\text{Sensitivität} + \\text{Spezifität} - 1 = .63 + .93 - 1 = .56$\n\n:::\n",
    "supporting": [
      "rechenkompetenzen_diagnostik_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}