<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>lst – Übungsheft</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5bf7ca59d8cc7f7a8155307016a58e21.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Übungsheft</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">FAQs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../sections/software/software.html"> 
<span class="menu-text">Software und Literatur</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-themenabschnitte" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Themenabschnitte</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-themenabschnitte">    
        <li>
    <a class="dropdown-item" href="../../sections/rechenkompetenzen/rechenkompetenzen.html">
 <span class="dropdown-text">1. Grundlegende Rechenkompetenzen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/rechenkompetenzen_diagnostik/rechenkompetenzen_diagnostik.html">
 <span class="dropdown-text">2. Rechenkompetenzen der Diagnostik</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/diagnostischer_prozess/diagnostischer_prozess.html">
 <span class="dropdown-text">3. Der Diagnostische Prozess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/konfidenzintervalle/konfidenzintervalle.html">
 <span class="dropdown-text">4. Konfidenzintervalle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/datenmatrizen/datenmatrizen.html">
 <span class="dropdown-text">5. Datenmatrizen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/rasch_modell/rasch_modell.html">
 <span class="dropdown-text">6. Das Rasch-Modell</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/pl2_pl3/pl2_pl3.html">
 <span class="dropdown-text">7. 2PL- und 3PL-Modelle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/polytom/polytom.html">
 <span class="dropdown-text">8. IRT-Modelle für Polytome Daten</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/thurstonian_irt/thurstonian_irt.html">
 <span class="dropdown-text">9. Thurstonian IRT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/adaptives_testen/adaptives_testen.html">
 <span class="dropdown-text">10. Adaptives Testen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/ktt_messmodelle/ktt_messmodelle.html">
 <span class="dropdown-text">10. KTT Messmodelle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../sections/lst/lst.html">
 <span class="dropdown-text">11. Latent-State-Trait Modelle</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-zusatzmaterial" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Zusatzmaterial</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-zusatzmaterial">    
        <li>
    <a class="dropdown-item" href="../../zusatzmaterial/pcm_beispiel/pcm_beispiel.html">
 <span class="dropdown-text">Beispielrechnung PCM</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../sections/mitwirkende/mitwirkende.html"> 
<span class="menu-text">Mitwirkende</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#latent-state-trait-modelle" id="toc-latent-state-trait-modelle" class="nav-link active" data-scroll-target="#latent-state-trait-modelle">Latent State-Trait Modelle</a>
  <ul class="collapse">
  <li><a href="#pfaddarstellung-von-lst-modellen" id="toc-pfaddarstellung-von-lst-modellen" class="nav-link" data-scroll-target="#pfaddarstellung-von-lst-modellen">Pfaddarstellung von LST-Modellen</a></li>
  <li><a href="#von-der-pfaddarstellung-zu-modellgleichungen" id="toc-von-der-pfaddarstellung-zu-modellgleichungen" class="nav-link" data-scroll-target="#von-der-pfaddarstellung-zu-modellgleichungen">Von der Pfaddarstellung zu Modellgleichungen</a></li>
  <li><a href="#varianzzerlegung" id="toc-varianzzerlegung" class="nav-link" data-scroll-target="#varianzzerlegung">Varianzzerlegung</a></li>
  <li><a href="#datenbeispiel" id="toc-datenbeispiel" class="nav-link" data-scroll-target="#datenbeispiel">Datenbeispiel</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="latent-state-trait-modelle" class="level1">
<h1>Latent State-Trait Modelle</h1>
<p>Latent State-Trait (LST) Modelle erweitern die Grundgleichung der KTT für Situationen, in denen mehrere Messzeitpunkte vorliegen.</p>
<section id="pfaddarstellung-von-lst-modellen" class="level2">
<h2 class="anchored" data-anchor-id="pfaddarstellung-von-lst-modellen">Pfaddarstellung von LST-Modellen</h2>
<p>Sie haben in der Vorlesung Pfaddarstellungen von LST Modellen, wie die folgende kennengelernt:</p>
<p><img src="images/lst_colour.png" class="img-fluid"></p>
<div class="callout-aufgabe">
<p>Beschreiben Sie die Datensituation, auf die das gezeigte LST Modell passen würde, genauer:</p>
<ul>
<li><p>Wie viele Messzeitpunkte liegen vor?</p></li>
<li><p>Wie viele Items gibt es zu jedem Messzeitpunkt?</p></li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Das Modell passt zu einer Situation, in der drei Items zu jeweils drei Messzeitpunkten erhoben wurden.</p>
</div>
</div>
</div>
<div class="callout-aufgabe">
<p>Welche der <span class="math inline">\(y\)</span>-Variablen beziehen sich jeweils auf das gleiche Item?</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Item 1: <span class="math inline">\(y_{11}\)</span>, <span class="math inline">\(y_{12}\)</span>, <span class="math inline">\(y_{13}\)</span></p>
<p>Item 2: <span class="math inline">\(y_{21}\)</span>, <span class="math inline">\(y_{22}\)</span>, <span class="math inline">\(y_{23}\)</span></p>
<p>Item 3: <span class="math inline">\(y_{31}\)</span>, <span class="math inline">\(y_{32}\)</span>, <span class="math inline">\(y_{33}\)</span></p>
</div>
</div>
</div>
<div class="callout-aufgabe">
<p>Welche der <span class="math inline">\(y\)</span>-Variablen beziehen sich jeweils auf den gleichen Messzeitpunkt?</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Messzeitpunkt 1: <span class="math inline">\(y_{11}\)</span>, <span class="math inline">\(y_{21}\)</span>, <span class="math inline">\(y_{31}\)</span></p>
<p>Messzeitpunkt 2: <span class="math inline">\(y_{12}\)</span>, <span class="math inline">\(y_{22}\)</span>, <span class="math inline">\(y_{32}\)</span></p>
<p>Messzeitpunkt 3: <span class="math inline">\(y_{13}\)</span>, <span class="math inline">\(y_{23}\)</span>, <span class="math inline">\(y_{33}\)</span></p>
</div>
</div>
</div>
<div class="callout-aufgabe">
<p>Welche Bedeutung haben die folgenden Parameter jeweils?</p>
<ul>
<li><p><span class="math inline">\(\epsilon_{21}\)</span> (“epsilon”)</p></li>
<li><p><span class="math inline">\(\lambda_{32}\)</span> (“lambda”)</p></li>
<li><p><span class="math inline">\(\tau_3\)</span> (“tau”)</p></li>
<li><p><span class="math inline">\(\zeta_2\)</span> (“zeta”)</p></li>
<li><p><span class="math inline">\(\gamma_1\)</span> (“gamma”)</p></li>
<li><p><span class="math inline">\(\xi\)</span> (“xi”)</p></li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\epsilon_{21}\)</span>: Residuum auf Item <span class="math inline">\(2\)</span> zu Zeitpunkt <span class="math inline">\(1\)</span>. Dieser Term nimmt wie ein Residuum in der Regression alles auf, was das Modell in Variable <span class="math inline">\(y_{21}\)</span> nicht vorhersagen kann.</p>
<p><span class="math inline">\(\lambda_{32}\)</span>: Faktorladung von Item <span class="math inline">\(3\)</span> zu Zeitpunkt <span class="math inline">\(2\)</span> auf dem latenten State <span class="math inline">\(\tau_2\)</span>. Der latente State beeinflusst das Item <span class="math inline">\(y_{32}\)</span> gewichtet um <span class="math inline">\(\lambda_{32}\)</span>.</p>
<p><span class="math inline">\(\tau_3\)</span>: Die latente State-Variable für Zeitpunkt <span class="math inline">\(3\)</span>. Diese Variable erfasst Varianzanteile, die den Items zum Zeitpunkt <span class="math inline">\(3\)</span> gemeinsam sind.</p>
<p><span class="math inline">\(\zeta_2\)</span>: State-spezifisches Residuum zu Zeitpunkt <span class="math inline">\(2\)</span>. Dieser Term enthält die Anteile am latenten State, die durch die den stabilen Trait nicht erklärt werden können.</p>
<p><span class="math inline">\(\gamma_1\)</span>: Faktorladung von State <span class="math inline">\(1\)</span> auf der stabilen Trait-Variable <span class="math inline">\(\xi\)</span>. Der stabile Trait beeinflusst den latenten State zu Zeitpunkt <span class="math inline">\(1\)</span> gewichtet um <span class="math inline">\(\gamma_1\)</span>.</p>
<p><span class="math inline">\(\xi\)</span>: Stabile Trait-Variable. Diese Variable erfasst Varianzanteile, die den drei latenten States gemeinsam sind.</p>
</div>
</div>
</div>
<p>Der Übersicht halber wurde der Personenindex <span class="math inline">\(m\)</span> in der Übersicht ignoriert. Das kommt manchmal vor, wenn aus dem Kontext ersichtlich ist, welche Variablen und Parameter personenspezifisch geschätzt werden.</p>
<div class="callout-aufgabe">
<p>Welche Variablen und Parameter sind personenspezifisch?</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Alle <span class="math inline">\(\epsilon\)</span>-Parameter</p>
<p>Alle <span class="math inline">\(y\)</span>-Variablen</p>
<p>Die <span class="math inline">\(\lambda\)</span>-Parameter nicht</p>
<p>Alle <span class="math inline">\(\tau\)</span>-Parameter</p>
<p>Alle <span class="math inline">\(\zeta\)</span>-Parameter</p>
<p>Die <span class="math inline">\(\gamma\)</span>-Parameter nicht</p>
<p>Der <span class="math inline">\(\xi\)</span>-Parameter</p>
</div>
</div>
</div>
</section>
<section id="von-der-pfaddarstellung-zu-modellgleichungen" class="level2">
<h2 class="anchored" data-anchor-id="von-der-pfaddarstellung-zu-modellgleichungen">Von der Pfaddarstellung zu Modellgleichungen</h2>
<p>Die Pfaddarstellung des Modells sehr nützlich, um schnell einen Überblick über das Modell zu bekommen. Hinter der Pfaddarstellung steckt aber, wie bei den Messmodellen auch, ein System linearer Modellgleichungen. In der folgenden Aufgabe werden Sie gebeten, die Modellgleichung für ein Item zu einem Zeitpunkt aufzuschreiben. Das wird vielen sicher nicht leicht fallen. Das ist nicht schlimm. Versuchen Sie es trotzdem einmal. Auch wenn Sie falsch liegen, haben Sie danach noch Gelegenheit zu üben.</p>
<div class="callout-aufgabe">
<p>Was ist die Modellgleichung für Item <span class="math inline">\(2\)</span> zu Zeitpunkt <span class="math inline">\(3\)</span>?</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Auf Basis der KTT setzt sich die Antwort aus den Komponenten <span class="math inline">\(\tau_{3}\)</span> und <span class="math inline">\(\epsilon_{23}\)</span> zusammen. <span class="math inline">\(\tau_3\)</span> ist für jedes Item zu Zeitpunkt <span class="math inline">\(3\)</span> identisch, wird aber für jedes Item anders gewichtet, hier mit <span class="math inline">\(\lambda_{23}\)</span>:</p>
<p><span class="math inline">\(y_{23} = \lambda_{23} \cdot \tau_{3} + \epsilon_{23}\)</span></p>
<p>Der latente State zu Zeitpunkt <span class="math inline">\(3\)</span> setzt sich zusammen aus dem stabilen Trait <span class="math inline">\(\xi\)</span> und einem messgelegenheitsspezifischen Residuum <span class="math inline">\(\zeta_3\)</span>. Der stabile Trait ist für jeden Messzeitpunkt identisch, wird aber für jeden Zeitpunkt anders gewichtet, hier mit <span class="math inline">\(\gamma_3\)</span>:</p>
<p><span class="math inline">\(\tau_{3} = \gamma_3 \cdot \xi + \zeta_3\)</span></p>
<p>Nun muss man nurnoch <span class="math inline">\(\tau_3\)</span> in die erste Gleichung einsetzen:</p>
<p><span class="math inline">\(y_{23} = \lambda_{23} \cdot (\gamma_3 \cdot \xi + \zeta_3) + \epsilon_{23}\)</span></p>
<p>Wenn man das lieber mag, kann man natürlich auch noch ausmultiplizieren:</p>
<p><span class="math inline">\(y_{23} = \lambda_{23} \cdot \gamma_3 \cdot \xi + \lambda_{23} \cdot \zeta_3 + \epsilon_{23}\)</span></p>
</div>
</div>
</div>
<p>Wie versprochen der zweite Versuch:</p>
<div class="callout-aufgabe">
<p>Was ist die Modellgleichung für Item <span class="math inline">\(1\)</span> zu Zeitpunkt <span class="math inline">\(2\)</span>?</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(y_{12} = \lambda_{12} \cdot \tau_{2} + \epsilon_{12}\)</span></p>
<p><span class="math inline">\(\tau_{2} = \gamma_2 \cdot \xi + \zeta_2\)</span></p>
<p><span class="math inline">\(y_{12} = \lambda_{12} \cdot (\gamma_2 \cdot \xi + \zeta_2) + \epsilon_{12}\)</span></p>
</div>
</div>
</div>
<p>Und noch einmal</p>
<div class="callout-aufgabe">
<p>Was ist die Modellgleichung für Item <span class="math inline">\(3\)</span> zu Zeitpunkt <span class="math inline">\(3\)</span>?</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(y_{33} = \lambda_{33} \cdot \tau_{3} + \epsilon_{33}\)</span></p>
<p><span class="math inline">\(\tau_{3} = \gamma_3 \cdot \xi + \zeta_3\)</span></p>
<p><span class="math inline">\(y_{33} = \lambda_{33} \cdot (\gamma_3 \cdot \xi + \zeta_3) + \epsilon_{33}\)</span></p>
</div>
</div>
</div>
<p>Die letzten drei Aufgaben sind meiner Meinung nach zentral für das tiefere Verständnis, denn die Pfaddarstellung <em>ist</em> nicht das Modell, sondern eine nützliche Darstellungsweise. Um tiefer mit einem Modell arbeiten zu können, sollte man auch mit der Gleichungsebene umgehen können. Diesen Umgang vertiefen wir nun noch einmal.</p>
<p>Ich nehme noch einmal ein Item zu einem Zeitpunkt heraus. Zum Beispiel Item <span class="math inline">\(3\)</span> zum Zeitpunkt <span class="math inline">\(1\)</span>. Aufgrund der vorherigen Aufgaben wissen Sie, dass die Grafik die folgende Modellgleichung für dieses Item impliziert:</p>
<p><span class="math display">\[y_{31} = \lambda_{31} \cdot (\gamma_3 \cdot \xi + \zeta_3) + \epsilon_{31}\]</span></p>
<p>Diese Darstellungsform ist schon sehr nützlich. Noch besser wäre es aber, eine allgemeine Modellgleichung für ein Item <span class="math inline">\(i\)</span> zu einem Zeitpunkt <span class="math inline">\(t\)</span> zu erhalten.</p>
<div class="callout-aufgabe">
<p>Bezeichnen Sie Items mit <span class="math inline">\(i\)</span> und Zeitpunkte mit <span class="math inline">\(t\)</span>. Verallgemeinern Sie die Modellgleichung des LST Modells.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[y_{it} = \lambda_{it} \cdot (\gamma_t \cdot \xi + \zeta_t) + \epsilon_{it}\]</span></p>
</div>
</div>
</div>
<p>Wie Sie aus einer vorherigen Aufgabe bereits wissen, sind einige der Gleichungskomponenten personenspezifisch. Da drei Indices schnell unübersichtlich würden, wurde das <span class="math inline">\(m\)</span> für Personen hier fallengelassen. Im Prinzip könnte man es aber noch hinzufügen.</p>
<div class="callout-aufgabe">
<p>Fügen Sie überall wo es sinnvoll ist einen Personenindex <span class="math inline">\(m\)</span> zur LST-Gleichung hinzu.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[y_{mit} = \lambda_{it} \cdot (\gamma_{t} \cdot \xi_m + \zeta_{mt}) + \epsilon_{mit}\]</span></p>
</div>
</div>
</div>
<p>Im Folgenden geht es aber ohne den Index <span class="math inline">\(m\)</span> weiter.</p>
</section>
<section id="varianzzerlegung" class="level2">
<h2 class="anchored" data-anchor-id="varianzzerlegung">Varianzzerlegung</h2>
<p>Nimmt man die Modellgleichung</p>
<p><span class="math display">\[y_{it} = \lambda_{it} \cdot (\gamma_t \cdot \xi + \zeta_t) + \epsilon_{it}\]</span></p>
<p>an, folgt daraus eine spezifische Varianzzerlegung für jeden Messwert. Man kann diese Varianzzerlegung herleiten. Das ist aber schon etwas fortgeschritten. Wenn Sie kein Interesse daran haben, können Sie die folgende Aufgabe getrost überspringen. Ich finde aber, es lohnt sich. :)</p>
<div class="callout-aufgabe">
<p>Sei</p>
<p><span class="math display">\[y_{it} = \lambda_{it} \cdot (\gamma_t \cdot \xi + \zeta_t) + \epsilon_{it}\]</span></p>
<p><span class="math display">\[= \lambda_{it} \cdot \gamma_t \cdot \xi + \lambda_{it} \cdot \zeta_t + \epsilon_{it}\]</span></p>
<p><span class="math display">\[= \textcolor{red}{(\lambda_{it} \cdot \gamma_t \cdot \xi)} + \textcolor{blue}{(\lambda_{it} \cdot \zeta_t)} + \textcolor{green}{\epsilon_{it}}\]</span></p>
<p>eine Zufallsvariable. Berechnen Sie <span class="math inline">\(Var(y_{it})\)</span>.</p>
<p>Nutzen Sie dafür die folgenden allgemeinen Zusammenhänge der Stochastik:</p>
<p><strong>Varianz der Summe von drei Zufallsvariablen</strong></p>
<p><span class="math display">\[Var(\textcolor{red}{X} + \textcolor{blue}{Y} + \textcolor{green}{Z})\]</span></p>
<p><span class="math display">\[= Var(X) + Var(Y) + Var(Z)\]</span></p>
<p><span class="math display">\[+ 2 \cdot Cov(X, Y) + 2 \cdot Cov(X, Z) + 2 \cdot Cov(Y, Z)\]</span></p>
<p><strong>Konstanten in Varianzen</strong></p>
<p><span class="math display">\[Var(a \cdot X) = a^2 \cdot Var(X)\]</span></p>
<p>Hier verstehen wir alles als “konstant”, was nicht personenspezifisch ist, also die <span class="math inline">\(\lambda\)</span>- und <span class="math inline">\(\gamma\)</span>-Parameter.</p>
<p><strong>Konstanten in Kovarianzen</strong></p>
<p><span class="math display">\[Cov(a \cdot X, b \cdot Y) = a \cdot b \cdot Cov(X, Y)\]</span></p>
<p>Nehmen Sie außerdem an, dass alle Kovarianzen nach Annahme Null sind.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Es ist</p>
<p><span class="math display">\[y_{it} = (\lambda_{it} \cdot \gamma_t \cdot \xi) + (\lambda_{it} \cdot \zeta_t) + \epsilon_{it}\]</span></p>
<p>Mit der angegebenen Formel für die Varianz der Summe von drei Zufallsvariablen gilt</p>
<p><span class="math display">\[Var(y_{it})\]</span></p>
<p><span class="math display">\[= Var(\lambda_{it} \cdot \gamma_t \cdot \xi) + Var(\lambda_{it} \cdot \zeta_t) + Var(\epsilon_{it})\]</span></p>
<p><span class="math display">\[+ 2 \cdot Cov(\lambda_{it} \cdot \gamma_t \cdot \xi, \lambda_{it} \cdot \zeta_t)\]</span></p>
<p><span class="math display">\[+ 2 \cdot Cov(\lambda_{it} \cdot \gamma_t \cdot \xi, \epsilon_{it})\]</span></p>
<p><span class="math display">\[+ 2 \cdot Cov(\lambda_{it} \cdot \zeta_t, \epsilon_{it})\]</span></p>
<p>Parameter, die sich nicht zwischen Personen unterscheiden (für die Formeln “Konstanten”), kann man quadrieren und als Faktor vor die Varianzen schreiben. Bei Kovarianzen muss man nicht quadrieren:</p>
<p><span class="math display">\[Var(y_{it})\]</span></p>
<p><span class="math display">\[= \lambda_{it}^2 \cdot \gamma_t^2 \cdot Var(\xi) + \lambda_{it}^2 \cdot Var(\zeta_t) + Var(\epsilon_{it})\]</span></p>
<p><span class="math display">\[+ 2 \cdot \lambda_{it}^2 \cdot \gamma_t \cdot Cov(\xi, \zeta_t)\]</span></p>
<p><span class="math display">\[+ 2 \cdot \lambda_{it} \cdot \gamma_t \cdot Cov(\xi, \epsilon_{it})\]</span></p>
<p><span class="math display">\[+ 2 \cdot \lambda_{it} \cdot Cov(\zeta_t, \epsilon_{it})\]</span></p>
<p>Nun folgen allehand Annahmen.</p>
<ol type="1">
<li><p>Der stabile Trait und das State-spezifische Residuum sind unabhängig voneinander und daher ist <span class="math inline">\(Cov(\xi, \zeta_t) = 0\)</span>.</p></li>
<li><p>Der stabile Trait und das Item- und Zeitpunkt-spezifische Residuum sind unabhängig voneinander und daher ist <span class="math inline">\(Cov(\xi, \epsilon_{it}) = 0\)</span>.</p></li>
<li><p>Das State-spezifische Residuum und das Item- und Zeitpunkt-spezifische Residuum sind unabhängig voneinander und daher ist <span class="math inline">\(Cov(\zeta_t, \epsilon_{it}) = 0\)</span>.</p></li>
</ol>
<p>Unter diesen Annahmen würde man für alle Kovarianzen Nullen einsetzen, sodass folgt:</p>
<p><span class="math display">\[Var(y_{it}) = \lambda_{it}^2 \cdot \gamma_t^2 \cdot Var(\xi) + \lambda_{it}^2 \cdot Var(\zeta_t) + Var(\epsilon_{it})\]</span></p>
<p>Nun sind wir schon am Ziel. Diese Varianzzerlegung finden Sie auf den Vorlesungsfolien wieder.</p>
</div>
</div>
</div>
<p>Das Ergebnis der letzten Aufgabe ist, dass sich die Varianz einer Variablen im LST Modell wie folgt zerlegen lässt:</p>
<p><span class="math display">\[Var(y_{it}) = \lambda_{it}^2 \cdot \gamma_t^2 \cdot Var(\xi) + \lambda_{it}^2 \cdot Var(\zeta_t) + Var(\epsilon_{it})\]</span></p>
<p>Das heißt, die Varianz der Antworten auf ein Item zu einem Zeitpunkt setzt sich additiv aus drei Komponenten zusammen.</p>
<ol type="1">
<li>aus einem Varianzanteil, der auf den stabilen Trait zurückzuführen ist:</li>
</ol>
<p><span class="math display">\[\lambda_{it}^2 \cdot \gamma_t^2 \cdot Var(\cdot \xi)\]</span></p>
<ol start="2" type="1">
<li>aus einem Varianzanteil, der auf das State-Residuum zurückzuführen ist:</li>
</ol>
<p><span class="math display">\[\lambda_{it}^2 \cdot Var(\zeta_t)\]</span></p>
<ol start="3" type="1">
<li>aus einem Varianzanteil, der auf den Messfehler zurückzuführen ist:</li>
</ol>
<p><span class="math display">\[Var(\epsilon_{it})\]</span></p>
<p>Die Anteile 1., 2. und 3. kann man jeweils durch die Gesamtvarianz der Variable teilen und erhält so eine Statistik darüber, welcher Anteil der Varianz eines Items auf den stabilen Trait, das State-Residuum oder den Messfehler zurückzuführen ist.</p>
<div class="callout-aufgabe">
<p>Setzen Sie die Formeln für diese Varianzanteile selbst zusammen, ohne auf den Folien nachzusehen.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Ich setze voraus, dass</p>
<p><span class="math display">\[
Var(y_{it}) = \lambda_{it}^2 \cdot \gamma_t^2 \cdot Var(\cdot \xi) + \lambda_{it}^2 \cdot Var(\zeta_t) + Var(\epsilon_{it})
\]</span></p>
<p>Man könnte <span class="math inline">\(Var(y_{it})\)</span> im Nenner aller Formeln auch in aufgelöster Form einsetzen. Das macht die Formeln aber schnell unübersichtlich.</p>
<p><strong>1. Varianzanteil aufgrund des stabilen Traits</strong></p>
<p>Diesen Anteil nennt man auch Konsistenz. Daher wird er hier mit <span class="math inline">\(Con(y_{it})\)</span> bezeichnet.</p>
<p><span class="math display">\[
Con(y_{it}) = \frac{
    \lambda_{it}^2 \cdot \gamma_t^2 \cdot Var(\cdot \xi)
}{
    Var(y_{it})
}
\]</span></p>
<p><strong>2. Varianzanteil aufgrund des State-Residuums</strong></p>
<p>Diesen Anteil nennt man auch Messgelegenheitsspezifität oder abgekürzt <span class="math inline">\(OSpe(y_{it})\)</span>:</p>
<p><span class="math display">\[
OSpe(y_{it}) = \frac{
    \lambda_{it}^2 \cdot Var(\zeta_t)
}{
    Var(y_{it})
}
\]</span></p>
<p><strong>3. Varianzanteil aufgrund des Messfehlers</strong></p>
<p>Man kann entsprechend auch einen Varianzanteil berechnen, der auf den Messfehler zurückzuführen ist:</p>
<p><span class="math display">\[
\frac{
    Var(\epsilon_{it})
}{
    Var(y_{it})
}
\]</span></p>
<p>Üblicherweise arbeitet man aber eher mit dem komplementären Varianzanteil. Diesen nennt man im LST-Kontext Reliabilität des Items <span class="math inline">\(i\)</span> zur Messgelegenheit <span class="math inline">\(t\)</span>:</p>
<p><span class="math display">\[
Rel(y_{it}) = 1 - \frac{
    Var(\epsilon_{it})
}{
    Var(y_{it})
}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="datenbeispiel" class="level2">
<h2 class="anchored" data-anchor-id="datenbeispiel">Datenbeispiel</h2>
<p>Ein Test mit fünf Items wurde zu vier Messzeitpunkten an jeweils <span class="math inline">\(784\)</span> Personen erhoben. Im Folgenden wird ein LST Modell auf die resultierenden Daten geschätzt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-19
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>lst <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="st">state1 =~ y_11 + y_21 + y_31 + y_41 + y_51</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="st">state2 =~ y_12 + y_22 + y_32 + y_42 + y_52</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="st">state3 =~ y_13 + y_23 + y_33 + y_43 + y_53</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="st">state4 =~ y_14 + y_24 + y_34 + y_44 + y_54</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="st">trait =~ state1 + state2 + state3 + state4</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>lst_fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(lst, <span class="at">data =</span> dat, <span class="at">estimator =</span> <span class="st">"MLR"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lst_fit, <span class="at">standardize =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 156 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        44

  Number of observations                           784

Model Test User Model:
                                              Standard      Scaled
  Test Statistic                               177.185     176.092
  Degrees of freedom                               166         166
  P-value (Chi-square)                           0.262       0.281
  Scaling correction factor                                  1.006
    Yuan-Bentler correction (Mplus variant)                       

Model Test Baseline Model:

  Test statistic                              8716.493    8673.003
  Degrees of freedom                               190         190
  P-value                                        0.000       0.000
  Scaling correction factor                                  1.005

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.999       0.999
  Tucker-Lewis Index (TLI)                       0.998       0.999
                                                                  
  Robust Comparative Fit Index (CFI)                         0.999
  Robust Tucker-Lewis Index (TLI)                            0.999

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)                710.621     710.621
  Scaling correction factor                                  1.022
      for the MLR correction                                      
  Loglikelihood unrestricted model (H1)        799.214     799.214
  Scaling correction factor                                  1.009
      for the MLR correction                                      
                                                                  
  Akaike (AIC)                               -1333.243   -1333.243
  Bayesian (BIC)                             -1128.009   -1128.009
  Sample-size adjusted Bayesian (SABIC)      -1267.731   -1267.731

Root Mean Square Error of Approximation:

  RMSEA                                          0.009       0.009
  90 Percent confidence interval - lower         0.000       0.000
  90 Percent confidence interval - upper         0.019       0.019
  P-value H_0: RMSEA &lt;= 0.050                    1.000       1.000
  P-value H_0: RMSEA &gt;= 0.080                    0.000       0.000
                                                                  
  Robust RMSEA                                               0.009
  90 Percent confidence interval - lower                     0.000
  90 Percent confidence interval - upper                     0.019
  P-value H_0: Robust RMSEA &lt;= 0.050                         1.000
  P-value H_0: Robust RMSEA &gt;= 0.080                         0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.023       0.023

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  state1 =~                                                             
    y_11              1.000                               0.181    0.653
    y_21              0.914    0.060   15.190    0.000    0.166    0.642
    y_31              0.891    0.063   14.213    0.000    0.162    0.622
    y_41              0.702    0.056   12.588    0.000    0.127    0.524
    y_51              1.138    0.076   15.013    0.000    0.206    0.719
  state2 =~                                                             
    y_12              1.000                               0.366    0.886
    y_22              1.160    0.034   34.148    0.000    0.424    0.904
    y_32              1.121    0.033   34.003    0.000    0.410    0.905
    y_42              1.303    0.034   37.951    0.000    0.477    0.920
    y_52              1.250    0.036   34.968    0.000    0.457    0.916
  state3 =~                                                             
    y_13              1.000                               0.277    0.813
    y_23              0.728    0.034   21.145    0.000    0.201    0.719
    y_33              0.797    0.034   23.541    0.000    0.220    0.744
    y_43              0.706    0.035   20.127    0.000    0.195    0.700
    y_53              0.524    0.031   17.172    0.000    0.145    0.609
  state4 =~                                                             
    y_14              1.000                               0.116    0.503
    y_24              1.469    0.134   10.972    0.000    0.171    0.660
    y_34              1.200    0.121    9.949    0.000    0.140    0.577
    y_44              1.184    0.123    9.656    0.000    0.138    0.567
    y_54              1.010    0.106    9.554    0.000    0.117    0.514
  trait =~                                                              
    state1            1.000                               0.742    0.742
    state2            2.627    0.175   14.998    0.000    0.966    0.966
    state3            1.816    0.135   13.453    0.000    0.883    0.883
    state4            0.594    0.065    9.175    0.000    0.687    0.687

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .y_11              0.044    0.003   16.239    0.000    0.044    0.573
   .y_21              0.039    0.002   16.727    0.000    0.039    0.588
   .y_31              0.041    0.003   16.229    0.000    0.041    0.614
   .y_41              0.043    0.002   18.435    0.000    0.043    0.725
   .y_51              0.040    0.002   15.944    0.000    0.040    0.483
   .y_12              0.037    0.002   16.451    0.000    0.037    0.215
   .y_22              0.040    0.003   15.194    0.000    0.040    0.183
   .y_32              0.037    0.002   16.767    0.000    0.037    0.180
   .y_42              0.042    0.003   15.867    0.000    0.042    0.154
   .y_52              0.040    0.002   16.365    0.000    0.040    0.162
   .y_13              0.039    0.003   15.573    0.000    0.039    0.339
   .y_23              0.038    0.002   18.156    0.000    0.038    0.483
   .y_33              0.039    0.002   16.543    0.000    0.039    0.446
   .y_43              0.040    0.002   17.951    0.000    0.040    0.510
   .y_53              0.036    0.002   17.327    0.000    0.036    0.629
   .y_14              0.040    0.002   16.607    0.000    0.040    0.747
   .y_24              0.038    0.003   14.319    0.000    0.038    0.565
   .y_34              0.039    0.002   16.415    0.000    0.039    0.667
   .y_44              0.040    0.002   17.513    0.000    0.040    0.679
   .y_54              0.038    0.002   17.359    0.000    0.038    0.736
   .state1            0.015    0.002    7.767    0.000    0.449    0.449
   .state2            0.009    0.004    2.547    0.011    0.067    0.067
   .state3            0.017    0.002    7.041    0.000    0.219    0.219
   .state4            0.007    0.001    6.113    0.000    0.528    0.528
    trait             0.018    0.002    7.442    0.000    1.000    1.000

R-Square:
                   Estimate
    y_11              0.427
    y_21              0.412
    y_31              0.386
    y_41              0.275
    y_51              0.517
    y_12              0.785
    y_22              0.817
    y_32              0.820
    y_42              0.846
    y_52              0.838
    y_13              0.661
    y_23              0.517
    y_33              0.554
    y_43              0.490
    y_53              0.371
    y_14              0.253
    y_24              0.435
    y_34              0.333
    y_44              0.321
    y_54              0.264
    state1            0.551
    state2            0.933
    state3            0.781
    state4            0.472</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modellimplizierte Varianz-Kovarianz-Matrix</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fitted</span>(lst_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$cov
      y_11  y_21  y_31  y_41  y_51  y_12  y_22  y_32  y_42  y_52  y_13  y_23
y_11 0.077                                                                  
y_21 0.030 0.067                                                            
y_31 0.029 0.027 0.068                                                      
y_41 0.023 0.021 0.021 0.059                                                
y_51 0.037 0.034 0.033 0.026 0.082                                          
y_12 0.048 0.043 0.042 0.033 0.054 0.171                                    
y_22 0.055 0.050 0.049 0.039 0.063 0.155 0.220                              
y_32 0.053 0.049 0.048 0.037 0.061 0.150 0.174 0.205                        
y_42 0.062 0.057 0.055 0.043 0.071 0.175 0.202 0.196 0.269                  
y_52 0.059 0.054 0.053 0.042 0.068 0.167 0.194 0.188 0.218 0.250            
y_13 0.033 0.030 0.029 0.023 0.037 0.086 0.100 0.097 0.113 0.108 0.116      
y_23 0.024 0.022 0.021 0.017 0.027 0.063 0.073 0.070 0.082 0.079 0.056 0.078
y_33 0.026 0.024 0.023 0.018 0.030 0.069 0.080 0.077 0.090 0.086 0.061 0.044
y_43 0.023 0.021 0.021 0.016 0.026 0.061 0.071 0.068 0.079 0.076 0.054 0.039
y_53 0.017 0.016 0.015 0.012 0.020 0.045 0.052 0.051 0.059 0.057 0.040 0.029
y_14 0.011 0.010 0.010 0.008 0.012 0.028 0.033 0.032 0.037 0.035 0.020 0.014
y_24 0.016 0.014 0.014 0.011 0.018 0.041 0.048 0.046 0.054 0.052 0.029 0.021
y_34 0.013 0.012 0.011 0.009 0.015 0.034 0.039 0.038 0.044 0.042 0.023 0.017
y_44 0.013 0.012 0.011 0.009 0.014 0.033 0.039 0.037 0.044 0.042 0.023 0.017
y_54 0.011 0.010 0.010 0.008 0.012 0.029 0.033 0.032 0.037 0.036 0.020 0.014
      y_33  y_43  y_53  y_14  y_24  y_34  y_44  y_54
y_11                                                
y_21                                                
y_31                                                
y_41                                                
y_51                                                
y_12                                                
y_22                                                
y_32                                                
y_42                                                
y_52                                                
y_13                                                
y_23                                                
y_33 0.088                                          
y_43 0.043 0.078                                    
y_53 0.032 0.028 0.057                              
y_14 0.016 0.014 0.010 0.054                        
y_24 0.023 0.020 0.015 0.020 0.067                  
y_34 0.019 0.017 0.012 0.016 0.024 0.059            
y_44 0.018 0.016 0.012 0.016 0.023 0.019 0.059      
y_54 0.016 0.014 0.010 0.014 0.020 0.016 0.016 0.052</code></pre>
</div>
</div>
<div class="callout-aufgabe">
<p>Beurteilen Sie den Modellfit anhand des CFI, SRMR, RMSEA und <span class="math inline">\(\chi^2\)</span>-Tests.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Man kann CFI, SRMR und RMSEA anhand gängiger, aber arbiträrer Cutoffs beurteilen:</p>
<p><span class="math inline">\(CFI = .999 &gt; .95\)</span></p>
<p><span class="math inline">\(SRMR = .023 &lt; 0.08\)</span></p>
<p><span class="math inline">\(RMSEA = .009 &lt; 0.08\)</span></p>
<p>Diese sprechen alle für einen sehr guten fit. Falls Ihnen in der Vorlesung andere Cutoffs mitgeteilt wurden, sollten Sie natürlich diese verwenden.</p>
<p>Der p-Wert des <span class="math inline">\(\chi^2\)</span>-Tests ist <span class="math inline">\(.262\)</span> und damit bei <span class="math inline">\(\alpha = 0.05\)</span> nicht signifikant. Die H0, dass die modellbasierte und beobachtete Varianz-Kovarianz-Matrix identisch sind, kann also nicht verworfen werden. Das spricht für einen sehr guten Modellfit.</p>
<p>Insbesondere ein nicht signifikanter <span class="math inline">\(\chi^2\)</span>-Test ist bei <span class="math inline">\(N = 784\)</span> Personen ungewöhnlich gut. In diesem Fall liegt das daran, dass die Daten nicht empirisch, sondern simuliert sind.</p>
</div>
</div>
</div>
<div class="callout-aufgabe">
<p>Zeichnen Sie eine Pfaddarstellung des Modells. Zeichnen Sie dort auch alle Parameter ein.</p>
</div>
<div class="callout-aufgabe">
<p>Suchen Sie im Output die</p>
<ul>
<li><p>unstandardisierten State-Ladungen <span class="math inline">\(\lambda_{it}\)</span></p></li>
<li><p>unstandardisierten Trait-Ladungen <span class="math inline">\(\gamma_t\)</span></p></li>
<li><p>unstandardisierte Trait-Varianz <span class="math inline">\(Var(\xi)\)</span></p></li>
<li><p>unstandardisierte State-Varianz <span class="math inline">\(Var(\tau_t)\)</span></p></li>
<li><p>unstandardisierten State-Residuen <span class="math inline">\(Var(\zeta_t)\)</span></p></li>
<li><p>unstandardisierten Item-Residuen <span class="math inline">\(\epsilon_{it}\)</span></p></li>
<li><p>Item Varianzen <span class="math inline">\(y_{it}\)</span></p></li>
</ul>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>unstandardisierten State-Ladungen <span class="math inline">\(\lambda_{it}\)</span></li>
</ul>
<p>z.B. bei <code>state1 =~ y_11</code> in der Spalte Estimate</p>
<ul>
<li>unstandardisierten Trait-Ladungen <span class="math inline">\(\gamma_t\)</span></li>
</ul>
<p>z.B. bei <code>trait =~ state1</code> in der Spalte Estimate</p>
<ul>
<li>unstandardisierte Trait-Varianz <span class="math inline">\(Var(\xi)\)</span></li>
</ul>
<p>Unter Variances in der Zeile <code>trait</code> und der Spalte Estimate</p>
<ul>
<li>unstandardisierte State-Varianz <span class="math inline">\(Var(\tau_t)\)</span></li>
</ul>
<p>Diesen Wert findet man nicht im Output, da <span class="math inline">\(\tau_t\)</span> im Modell in einen stabilen Trait und ein State-spezifisches Residuum dekomponiert wird. Man könnte ihn aber berechnen.</p>
<ul>
<li>unstandardisierten State-Residuen <span class="math inline">\(Var(\zeta_t)\)</span></li>
</ul>
<p>Unter Variances, z.B. in der Zeile <code>state1</code> in der Spalte Estimate</p>
<ul>
<li>unstandardisierten Item-Residuen <span class="math inline">\(\epsilon_{it}\)</span></li>
</ul>
<p>Die unstandardisierten Item-Residuen findet man nicht im Output. Sie sind personenspezifisch und würden <span class="math inline">\(N\)</span> Zeilen Output erfordern. Man findet aber die Residualvarianzen, nämlich unter Variances bei den Itemnamen.</p>
<ul>
<li>Item Varianzen <span class="math inline">\(Var(y_{it})\)</span></li>
</ul>
<p>Die Itemvarianzen finden Sie auf der Hauptdiagonale der modellimplizierten Varianz-Kovarianz-Matrix. Man könnte sie aber auch aus den Parametern ausrechnen, wenn die Matrix nicht gegeben ist (siehe Formel oben).</p>
</div>
</div>
</div>
<div class="callout-aufgabe">
<p>Berechnen Sie anhand des Outputs die Konsistenz, Messgelegenheitspezifität und Reliabilität von Item <span class="math inline">\(4\)</span> zu Zeitpunkt <span class="math inline">\(3\)</span>.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Gesucht</strong></p>
<p><span class="math display">\[
Con(y_{43}) = \frac{
    \lambda_{43}^2 \cdot \gamma_3^2 \cdot Var(\xi)
}{
    Var(y_{43})
}
\]</span></p>
<p><span class="math display">\[
OSpe(y_{43}) = \frac{
    \lambda_{43}^2 \cdot Var(\zeta_3)
}{
    Var(y_{43})
}
\]</span></p>
<p><span class="math display">\[
Rel(y_{43}) = 1 - \frac{
    Var(\epsilon_{43})
}{
    Var(y_{43})
}
\]</span></p>
<p><strong>Gegeben</strong></p>
<p>Aus dem Output und der modellimplizierten Varianz-Kovarianz-Matrix:</p>
<p><span class="math inline">\(\lambda_{43} = 0.706\)</span></p>
<p><span class="math inline">\(\gamma_3 = 1.816\)</span></p>
<p><span class="math inline">\(Var(\xi) = 0.018\)</span></p>
<p><span class="math inline">\(Var(\zeta_3) = 0.017\)</span></p>
<p><span class="math inline">\(Var(\epsilon_{43}) = 0.040\)</span></p>
<p><span class="math inline">\(Var(y_{43}) = 0.078\)</span></p>
<p><strong>Einsetzen</strong></p>
<p><span class="math display">\[
Con(y_{43})
=\frac{0.706^2\cdot 1.816^2\cdot 0.018}{0.078}
\approx 0.38
\]</span></p>
<p><span class="math display">\[
OSpe(y_{43})
=\frac{0.706^2\cdot 0.017}{0.078}
\approx 0.11
\]</span></p>
<p><span class="math display">\[
Rel(y_{43})
=1-\frac{0.040}{0.078}
\approx 0.49
\]</span></p>
<p>Zur Überprüfung kann man noch einmal schauen, ob der berechnete Wert von <span class="math inline">\(Rel(y_{43})\)</span> dem Wert bei R-Square im Output entspricht. Das ist hier der Fall.</p>
</div>
</div>
</div>
<div class="callout-aufgabe">
<p>Zum Weiterüben finden Sie hier die Konsistenzen und Messgelegenheitsspezifitäten aller Items zu allen Zeitpunkten. Die Reliabilitäten können Sie unter R-Square im Output ablesen.</p>
<p>Beachten Sie, dass es zu Rundungsabweichungen kommen kann, da die Lösungen mit ungerundeten Parameterschätzungen berechnet wurden.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Lösung">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Item: 1 Zeitpunkt: 1 Konsistenz: 0.24 M.Spezifität: 0.19"
[1] "Item: 1 Zeitpunkt: 2 Konsistenz: 0.73 M.Spezifität: 0.05"
[1] "Item: 1 Zeitpunkt: 3 Konsistenz: 0.52 M.Spezifität: 0.15"
[1] "Item: 1 Zeitpunkt: 4 Konsistenz: 0.12 M.Spezifität: 0.13"
[1] "Item: 2 Zeitpunkt: 1 Konsistenz: 0.23 M.Spezifität: 0.18"
[1] "Item: 2 Zeitpunkt: 2 Konsistenz: 0.76 M.Spezifität: 0.06"
[1] "Item: 2 Zeitpunkt: 3 Konsistenz: 0.4 M.Spezifität: 0.11"
[1] "Item: 2 Zeitpunkt: 4 Konsistenz: 0.21 M.Spezifität: 0.23"
[1] "Item: 3 Zeitpunkt: 1 Konsistenz: 0.21 M.Spezifität: 0.17"
[1] "Item: 3 Zeitpunkt: 2 Konsistenz: 0.76 M.Spezifität: 0.06"
[1] "Item: 3 Zeitpunkt: 3 Konsistenz: 0.43 M.Spezifität: 0.12"
[1] "Item: 3 Zeitpunkt: 4 Konsistenz: 0.16 M.Spezifität: 0.18"
[1] "Item: 4 Zeitpunkt: 1 Konsistenz: 0.15 M.Spezifität: 0.12"
[1] "Item: 4 Zeitpunkt: 2 Konsistenz: 0.79 M.Spezifität: 0.06"
[1] "Item: 4 Zeitpunkt: 3 Konsistenz: 0.38 M.Spezifität: 0.11"
[1] "Item: 4 Zeitpunkt: 4 Konsistenz: 0.15 M.Spezifität: 0.17"
[1] "Item: 5 Zeitpunkt: 1 Konsistenz: 0.28 M.Spezifität: 0.23"
[1] "Item: 5 Zeitpunkt: 2 Konsistenz: 0.78 M.Spezifität: 0.06"
[1] "Item: 5 Zeitpunkt: 3 Konsistenz: 0.29 M.Spezifität: 0.08"
[1] "Item: 5 Zeitpunkt: 4 Konsistenz: 0.12 M.Spezifität: 0.14"</code></pre>
</div>
</div>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>